.TH LMC "1" "November 2013" "lmc 1.0" "User Commands"
.SH NAME
lmc \- manual page for lmc 1.0
.SH SYNOPSIS
.B lmvm
[\fIOPTION\fR] [\fIfilename\fR]
.SH DESCRIPTION
LMC \- little man computer virtual machine.
.SH OPTIONS
.TP
\fB\-h\fR, \-?            \fB\-\-help\fR
Print a helpful message and exit.
.TP
\fB\-v\fR                \fB\-\-version\fR
Print version information and exit.
.SH "REPORTING BUGS"
Report bugs to <linuxgeek@gmail.com>.
